# Generated by Django 2.2.16 on 2020-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=255, verbose_name='Отчество')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('dob', models.DateField(max_length=8)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мобильный номер')),
                ('work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочий номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('socials', models.CharField(max_length=255, verbose_name='Соц. Сети')),
            ],
        ),
    ]
